Vitis AI 6.3 GA release

diff --git a/versal_2ve/examples/cpp_examples/Makefile b/versal_2ve/examples/cpp_examples/Makefile
--- a/versal_2ve/examples/cpp_examples/Makefile
+++ b/versal_2ve/examples/cpp_examples/Makefile
@@ -13,34 +13,20 @@
  # See the License for the specific language governing permissions and
  # limitations under the License.
 ###########################################################################
-.DEFAULT_GOAL:= default
-
-default: install-pre-commit-hook all
-
-# Source of the pre-commit hook
-HOOK_SRC := ../../githooks/pre-commit.hook
-
-# Destination in the repo
-HOOK_DEST := ../../.git/hooks/pre-commit
-
-# Install the pre-commit hook
-install-pre-commit-hook:
-	@echo "Installing pre-commit hook..."
-	@if [ -f $(HOOK_SRC) ]; then \
-	    cp $(HOOK_SRC) $(HOOK_DEST); \
-	    chmod +x $(HOOK_DEST); \
-	    echo "Pre-commit hook installed successfully."; \
-	fi
-
+.DEFAULT_GOAL:= all
 
 # All leaf apps with a local Makefile and an `install` target are built and packaged
 # into install/applications.tar.gz (see each subdir and common/install-app.mk where used).
-# Placeholder directories (TBD, no sources yet; see each README): vart_infer_async, vart_ml_async.
-SUBDIRS := ml_ort ml_vart x_plus_ml_ort x_plus_ml_vart spatial_mt_ml_ort vart_multimodel_seq vart_multi_tenancy vart_zerocopy vart_infer_async
-LIBSUBDIRS := common/utility_timer
+SUBDIRS := ml_ort ml_vart vart_llm x_plus_ml_ort x_plus_ml_vart spatial_mt_ml_ort vart_multimodel_seq vart_multi_tenancy vart_zerocopy vart_infer_async
+LIBSUBDIRS := common/utility_timer common/utils/llm_sampler common/utils/llm_tokenizer
+
 COMMON_UTILS_DIR := common/utils
 
-.PHONY: all clean install package libs apps $(SUBDIRS) $(LIBSUBDIRS)
+# Python example scripts installed to install/etc/vai/python/
+PYTHON_EXAMPLES_DIR := ../python_examples
+INSTALL_VAI_PYTHON := install/etc/vai/python
+
+.PHONY: all clean install package libs apps $(SUBDIRS) $(LIBSUBDIRS) install-python-examples
 
 libs: $(LIBSUBDIRS)
 
@@ -61,6 +47,18 @@ clean:
 	done
 	rm -rf install applications.tar.gz
 
+install-python-examples:
+	@if [ -d $(PYTHON_EXAMPLES_DIR) ]; then \
+		mkdir -p $(INSTALL_VAI_PYTHON); \
+		for f in $(PYTHON_EXAMPLES_DIR)/*.py; do \
+			[ -f "$$f" ] || continue; \
+			cp "$$f" $(INSTALL_VAI_PYTHON)/; \
+		done; \
+		echo "Installed python example scripts to $(INSTALL_VAI_PYTHON)"; \
+	else \
+		echo "$(PYTHON_EXAMPLES_DIR) not found, skipping python example install"; \
+	fi
+
 install: apps
 	@for dir in $(LIBSUBDIRS); do \
 		$(MAKE) -C $$dir install; \
@@ -69,6 +67,7 @@ install: apps
 	@for dir in $(SUBDIRS); do \
 		$(MAKE) -C $$dir install; \
 	done
+	@$(MAKE) install-python-examples
 
 all: install
 	@cd install && tar -czvf applications.tar.gz usr etc
